In [6]:
print('hello')

hello


In [7]:
b = 3
a = b + 4
a

7

In [11]:
a = ['apple', 'orange', 'kiwi', 'grape', 'cherry']
print(a[4])
print(a[1:3])
print(a[:3])
print(a[2:])

cherry
['orange', 'kiwi']
['apple', 'orange', 'kiwi']
['kiwi', 'grape', 'cherry']


In [15]:
b = [['apple', 2], ['orange', 5], ['kiwi', 4], ['grape', 3], ['cherry',
25]]
print(b[1][0])

orange


In [16]:
a.append('peach')

In [17]:
a

['apple', 'orange', 'kiwi', 'grape', 'cherry', 'peach']

In [18]:
a.remove('apple')

In [19]:
a

['orange', 'kiwi', 'grape', 'cherry', 'peach']

In [21]:
d = [5, -2, 7, 3, -4, 10]
len(d)

6

In [30]:
d_new = ['positive' if i>0 else 'negative' for i in d if i<9]

In [31]:
d_new

['positive', 'negative', 'positive', 'positive', 'negative']

In [8]:
import numpy as np

In [40]:
np.array([1,3,'4.5'])

array(['1', '3', '4.5'], dtype='<U21')

In [41]:
np.array([1,2,3,4], dtype ='float')

array([1., 2., 3., 4.])

In [43]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [47]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [50]:
np.random.random((4,5))

array([[0.11161331, 0.70029848, 0.08163668, 0.55990956, 0.11993326],
       [0.89860787, 0.41840003, 0.12928289, 0.39012948, 0.88370403],
       [0.27099538, 0.99655405, 0.35426493, 0.12151143, 0.68333369],
       [0.00698012, 0.08623057, 0.9325027 , 0.30170408, 0.19820392]])

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
x3 = np.random.randint(10, size=(3,4,5))
x3

array([[[0, 0, 7, 0, 8],
        [7, 4, 6, 7, 1],
        [8, 6, 0, 4, 9],
        [0, 6, 6, 3, 7]],

       [[4, 2, 2, 4, 6],
        [6, 5, 5, 2, 6],
        [2, 5, 7, 0, 6],
        [2, 2, 4, 1, 0]],

       [[4, 0, 4, 0, 3],
        [8, 5, 3, 6, 3],
        [5, 7, 2, 6, 7],
        [6, 8, 0, 9, 1]]])

In [59]:
print(x3[1, 2:4])

[[2 5 7 0 6]
 [2 2 4 1 0]]


In [63]:
a = [1,2]
b = a[1]
b = 4
print(b)
print(a)

4
[1, 2]


In [66]:
a = np.array([1,2]) #np array
b=a[1]
b=4
print(a)
print(b)

[1 2]
4


In [6]:
a = [1,2,3,4,5]
b = a[2:4]
print(b)
b[1] = 8
print(b)
print(a)

[3, 4]
[3, 8]
[1, 2, 3, 4, 5]


In [14]:
c = np.array((1,2,3,4,5))
d = c[2:4].copy()
print(d)
d[1] = 8
print(d)
print(c)

[3 4]
[3 8]
[1 2 3 4 5]


### Not a copy, but a view of the array. Need to explicitly state that it is a copy with .copy()
